name: bluebuild
on:
  schedule:
    - cron:
        "00 06 * * *" # build at 06:00 UTC every day
        # (20 minutes after last ublue images start building)
  push:
    paths-ignore: # don't rebuild if only documentation has changed
      - "**.md"

  pull_request:
  workflow_dispatch: # allow manually triggering builds
concurrency:
  # only run one build at a time
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false # stop GH from cancelling all matrix builds if one fails
      matrix:
        recipe:
          # !! Add your recipes here
          - recipe.yml
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Custom Image via Jenkinsfile Runner
        uses: jenkinsci/jenkinsfile-runner-github-actions/jenkinsfile-runner-prepackaged@04c450a7cd2001baf0d5bf263c2d421b958659d1
        env:
          JENKINS_VERSION: 2.138.2
          GITHUB_TOKEN: ${{ github.token }}
          SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
          CI_RECIPE: ${{ matrix.recipe }}
          CI_EVENT_NAME: ${{ github.event_name }}
          CI_REF: ${{ github.ref }}
          CI_SHA: ${{ github.sha }}
          CI_PR_NUMBER: ${{ github.event.number }}
          CI_SOURCE_WORKSPACE: ${{ github.workspace }}
          CI_REGISTRY: ghcr.io
          CI_REGISTRY_TOKEN: ${{ github.token }}
          CI_REGISTRY_USER: ${{ github.actor }}
